name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Install dependencies
        run: npm install
        
      - name: Install validators
        run: |
          npm install -g htmlhint stylelint eslint
          npm install -g stylelint-config-standard
          
      - name: Validate HTML
        run: htmlhint src/**/*.html
        
      - name: Validate CSS
        run: stylelint "src/**/*.css"
        
      - name: Validate JavaScript
        run: eslint "src/**/*.js" --fix