name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Install dependencies
        run: npm ci
          
      - name: Validate HTML
        run: npx htmlhint "src/**/*.html"
        
      - name: Validate CSS
        run: npx stylelint "src/**/*.css"
        
      - name: Validate JavaScript
        run: npx eslint "src/**/*.js" --fix

