name: CI/CD Landing Page

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'package.json'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Verify package.json
        run: |
          if [ ! -f "package.json" ]; then
            echo "❌ package.json não encontrado!"
            exit 1
          fi
          echo "✅ Arquivo package.json verificado"

      - name: Install dependencies
        run: npm ci --audit

      - name: Build project
        run: npm run build

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4